// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzcfscckmbmkuiuhiivc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Y2ZzY2NrbWJta3VpdWhpaXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTExMjksImV4cCI6MjA1OTIyNzEyOX0.1ruLrlCv3UG16F9FfjyVGvNaMfBQJbOJ7q_UEN1cmo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);